## Датасет собран из базы данных переписи 1994 года и содержит данные о доходах.
### Информация о данных:
* age: continuous.
* workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.
* fnlwgt: continuous.
* education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, * Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.
* education-num: continuous.
* marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.
* occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.
* relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.
* race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.
* sex: Female, Male.
* capital-gain: continuous.
* capital-loss: continuous.
* hours-per-week: continuous.
* native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.
* salary: >50K,<=50K

## Проведите анализ данных при помощи Pandas выполнив поставленные задачи.
####

In [2]:
import pandas as pd

In [3]:
# загружаем датасет
df = pd.read_csv("./data/adult.data.csv")
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,salary
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

**1. Посчитайте, сколько мужчин и женщин (признак *sex*) представлено в этом датасете**

In [7]:
# your code
males = (df['sex']=='Male').sum()
females= (df['sex'] == 'Female').sum()

print(f"Males: {males}\nFemales: {females}")

Males: 21790
Females: 10771

**2. Каков средний возраст мужчин (признак *age*) по всему датасету?**

In [3]:
# your code
average_age_man = df[df["sex"] == 'Male']['age'].mean()
average_age_man

np.float64(39.43354749885268)

**3. Какова доля граждан Соединенных Штатов (признак *native-country*)?**

In [11]:
# your code
use_proportion = (df['native-country'] == 'United-States').mean()
use_proportion

np.float64(0.895857006848684)

**4-5. Рассчитайте среднее значение и среднеквадратичное отклонение возраста тех, кто получает более 50K в год (признак *salary*) и тех, кто получает менее 50K в год**

In [16]:
# your code
more_50_k = df[df['salary'] == '>50K']['age'].agg(['mean','std'])
less_or_eq_50_k = df[df['salary'] == '<=50K']['age'].agg(['mean', 'std'])
print(f"More then 50k: Age avarage is {more_50_k['mean']}, std is {more_50_k['std']}")
print(f"Less then or equal 50k: Age avarage is {less_or_eq_50_k['mean']}, std is {less_or_eq_50_k['std']}")

More then 50k: Age avarage is 44.24984058155847, std is 10.51902771985177
Less then or equal 50k: Age avarage is 36.78373786407767, std is 14.020088490824813

**6. Правда ли, что люди, которые получают больше 50k, имеют минимум высшее образование? (признак *education – Bachelors, Prof-school, Assoc-acdm, Assoc-voc, Masters* или *Doctorate*)**

In [17]:
df['education'].value_counts()

education
HS-grad         10501
Some-college     7291
Bachelors        5355
Masters          1723
Assoc-voc        1382
11th             1175
Assoc-acdm       1067
10th              933
7th-8th           646
Prof-school       576
9th               514
12th              433
Doctorate         413
5th-6th           333
1st-4th           168
Preschool          51
Name: count, dtype: int64

In [20]:
# your code
indecator = (
    (df['salary'] == '>50K') &
    (df['education'].isin(educations))
).mean() / (df['salary'] == '>50K').mean()

if indecator == 1.0:
    print('Assumption is true')
else:
    print('Assumption is False')

Assumption is False

**7. Выведите статистику возраста для каждой расы (признак *race*) и каждого пола. Используйте *groupby* и *describe*. Найдите таким образом максимальный возраст мужчин расы *Asian-Pac-Islander*.**

In [28]:
# your code
static_age_by_race = df[['age', 'race']].groupby('race').describe()
static_age_by_sex = df[['age', 'sex']].groupby('sex').describe()

print(static_age_by_race)
print(static_age_by_sex)


print(f"максимальный возраст мужчин расы Asian-Pac-Islander : {static_age_by_race.loc['Asian-Pac-Islander', ('age', 'max')]}")

                        age                                                \
                      count       mean        std   min   25%   50%   75%
race
Amer-Indian-Eskimo    311.0  37.173633  12.447130  17.0  28.0  35.0  45.5
Asian-Pac-Islander   1039.0  37.746872  12.825133  17.0  28.0  36.0  45.0
Black                3124.0  37.767926  12.759290  17.0  28.0  36.0  46.0
Other                 271.0  33.457565  11.538865  17.0  25.0  31.0  41.0
White               27816.0  38.769881  13.782306  17.0  28.0  37.0  48.0


                     max
race
Amer-Indian-Eskimo  82.0
Asian-Pac-Islander  90.0
Black               90.0
Other               77.0
White               90.0
            age
          count       mean        std   min   25%   50%   75%   max
sex
Female  10771.0  36.858230  14.013697  17.0  25.0  35.0  46.0  90.0
Male    21790.0  39.433547  13.370630  17.0  29.0  38.0  48.0  90.0
максимальный возраст мужчин расы Asian-Pac-Islander : 90.0

**8. Среди кого больше доля зарабатывающих много (>50K): среди женатых или холостых мужчин (признак *marital-status*)? Женатыми считаем тех, у кого *marital-status* начинается с *Married* (Married-civ-spouse, Married-spouse-absent или Married-AF-spouse), остальных считаем холостыми.**

In [35]:
# your code
df['marital-status'].value_counts()
married_status =['Married-civ-spouse', 'Married-spouse-absent' ,'Married-AF-spouse']

p_married = ((df['marital-status'].isin(married_status)) & (df['salary'] == '>50K')).mean()
p_unmarried = ((~df['marital-status'].isin(married_status)) & (df['salary'] == '>50K')).mean()

indecator = p_married/p_unmarried
print(indecator) # if indecator > 1 means the married poeple is more then unmarried

# Other way my adding new column and group by it

df['is_married'] = df['marital-status'].isin(married_status)

result = df.groupby('is_married')['salary'].apply(lambda s: (s == '>50K').mean())
result

6.095927601809954

is_married
False    0.064454
True     0.436920
Name: salary, dtype: float64

**9. Какое максимальное число часов человек работает в неделю (признак *hours-per-week*)? Сколько людей работают такое количество часов и каков среди них процент зарабатывающих много?**

In [43]:
# your code

max_hours_per_week = df['hours-per-week'].max()
workers = df.loc[df['hours-per-week'] == max_hours_per_week]
count_workers = workers.shape[0]
percent_high_income = (workers['salary'] == '>50K').mean()

print(f"Max hours per week workers spend at work :{max_hours_per_week}, they are {count_workers} wroker and the prec ")

**10. Посчитайте среднее время работы (*hours-per-week*) зарабатывающих мало и много (*salary*) для каждой страны (*native-country*).**

In [9]:
# your code
df.groupby(['native-country', 'salary'])['hours-per-week'].mean()

native-country  salary
?               <=50K     40.164760
                >50K      45.547945
Cambodia        <=50K     41.416667
                >50K      40.000000
Canada          <=50K     37.914634
                            ...
United-States   >50K      45.505369
Vietnam         <=50K     37.193548
                >50K      39.200000
Yugoslavia      <=50K     41.600000
                >50K      49.500000
Name: hours-per-week, Length: 82, dtype: float64

**11.Сгруппируйте людей по возрастным группам *young*, *adult*, *retiree*, где:**
* *young* соответствует 16-35 лет
* *adult* - 35-70 лет
* *retiree* - 70-100 лет

**Проставьте название соответсвтуещей группы для каждого человека в новой колонке AgeGroup**

In [11]:
# your code
import numpy as np

conditions = [
    df['age'].between(16,35,inclusive='left'),
    df['age'].between(35,70, inclusive='left'),
    df['age'].between(70,100, inclusive='both')
]
choices = ['young', 'adult', 'retiree']

df['AgeGroup'] = np.select(conditions, choices, default='unknown')

df[['age', 'AgeGroup']]

       age AgeGroup
0       39    adult
1       50    adult
2       38    adult
3       53    adult
4       28    young
...    ...      ...
32556   27    young
32557   40    adult
32558   58    adult
32559   22    young
32560   52    adult

[32561 rows x 2 columns]

**12-13. Определите количество зарабатывающих >50K в каждой из возрастных групп (колонка AgeGroup), а также выведите название возрастной группы, в которой чаще зарабатывают больше 50К (>50K)**

In [17]:
# your code
counts = df.loc[df['salary'] == '>50K'].groupby('AgeGroup').size()
print(counts)
counts.idxmax()

AgeGroup
adult      6240
retiree     113
young      1488
dtype: int64

'adult'

**14. Сгруппируйте людей по типу занятости (колонка occupation) и определите количество людей в каждой группе. После чего напишите функциюю фильтрации filter_func, которая будет возвращать только те группы, в которых средний возраст (колонка age) не больше 40 и в которых все работники отрабатывают более 5 часов в неделю (колонка hours-per-week)**

In [23]:
# your code
groups_size = df.groupby('occupation').size()

def filter_func(group):
    return ( group['age'].mean() <40) and (group['hours-per-week'].min() >5 )

filterd_group = df.groupby('occupation').filter(filter_func)

print(groups_size)
print(filterd_group)

occupation
?                    1843
Adm-clerical         3770
Armed-Forces            9
Craft-repair         4099
Exec-managerial      4066
Farming-fishing       994
Handlers-cleaners    1370
Machine-op-inspct    2002
Other-service        3295
Priv-house-serv       149
Prof-specialty       4140
Protective-serv       649
Sales                3650
Tech-support          928
Transport-moving     1597
dtype: int64
       age    workclass  fnlwgt     education  education-num  \
442     24  Federal-gov  191073       HS-grad              9
1300    29  Federal-gov  301010  Some-college             10
14613   39  Federal-gov  227597       HS-grad              9
16111   24  Federal-gov  287988     Bachelors             13
18034   34  Federal-gov  172716          12th              8
18644   23  Federal-gov  163870  Some-college             10
18769   30  Federal-gov   76313       HS-grad              9
25799   46  Federal-gov  344415       Masters             14
32316   23  Federal-gov  173851       HS-grad              9

           marital-status    occupation    relationship                race  \
442         Never-married  Armed-Forces       Own-child               White
1300        Never-married  Armed-Forces   Not-in-family               Black
14613       Never-married  Armed-Forces   Not-in-family               White
16111       Never-married  Armed-Forces   Not-in-family               White
18034  Married-civ-spouse  Armed-Forces         Husband               White
18644       Never-married  Armed-Forces  Other-relative               White
18769  Married-civ-spouse  Armed-Forces  Other-relative  Amer-Indian-Eskimo
25799  Married-civ-spouse  Armed-Forces         Husband               White
32316       Never-married  Armed-Forces   Not-in-family               White

        sex  capital-gain  capital-loss  hours-per-week native-country salary  \
442    Male             0             0              40  United-States  <=50K
1300   Male             0             0              60  United-States  <=50K
14613  Male             0             0              50  United-States  <=50K
16111  Male             0             0              40  United-States  <=50K
18034  Male             0             0              40  United-States  <=50K
18644  Male             0             0              40  United-States  <=50K
18769  Male             0             0              48  United-States  <=50K
25799  Male             0          1887              40  United-States   >50K
32316  Male             0             0               8  United-States  <=50K

      AgeGroup
442      young
1300     young
14613    adult
16111    young
18034    young
18644    young
18769    young
25799    adult
32316    young